**MAESTRÍA EN INTELIGENCIA ARTIFICIAL APLICADA**

**Curso: TC5053 - Ciencia y analítica de datos**

Tecnológico de Monterrey

Prof Grettel Barceló Alonso

**Semana 3**
Bases, almacenes y manipulación de datos

---

*   NOMBRE: Vanessa Estopier Tinajero
*   MATRÍCULA: A01841600

---

En esta actividad usarás una base de datos relacional basada en el informe de participación y la lista del top 10 de Netflix. Incluye películas y programas de televisión, así como información sobre temporadas, métricas de visualización, fechas de estreno, duración y más, organizada en las siguientes tablas:

* `movie`: Información general de las películas.

* `tv_show`: Información general de los programas de televisión.

* `season`: Datos de las temporadas asociadas a cada programa de TV.

* `view_summary`: Métricas de visualización y rendimiento de películas o temporadas.

Revisa con detalle su esquema para que comprendas cómo se relacionan las tablas anteriores.

**NOTA IMPORTANTE:** Asegúrate de responder *explícitamente* todos los cuestionamientos.

`PyMySQL` es una librería escrita en Python puro que funciona como conector (*driver*) para motores de bases de datos MySQL, permitiendo abrir conexiones, ejecutar consultas SQL y recuperar resultados directamente desde programas en Python.

In [1]:
%pip install -q pymysql

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.7/46.7 kB 965.2 kB/s eta 0:00:00

`SQLAlchemy` es una librería de Python que facilita la interacción con bases de datos y permite mantener un pool de conexiones eficiente, gestionar *commits* y *rollbacks* de forma automática y asegurar que múltiples conexiones simultáneas se manejen de manera segura, incluso cuando se ejecutan consultas SQL “puras”

In [2]:
# Importa las librerías necesarias
import pymysql
import sqlalchemy as sqla
import pandas as pd

Se crea una conexión (`conn`) para luego invocar declaraciones SQL.

In [3]:
# motor+driver://usuarioBD:clave@ipHostDBMS:puerto/esquema
# pool_recycle controla el tiempo máximo de vida de una conexión en el pool (3600 segundos = 1 hora)
db = sqla.create_engine('mysql+pymysql://mnaTC5053User:mnaTC5053Pass!@20.127.169.219:3306/Netflix', pool_recycle=3600)
conn = db.connect()

Para que tus consultas sean más legibles y fáciles de mantener, puedes usar este formato multilínea con comillas triples y `sqla.text()`. Por ejemplo:

```
query = sqla.text("""
  SELECT ---
  FROM ---
  WHERE ---
""")
pd.read_sql(query, conn)
```

1.	Extrae toda la información de las películas que duran más de 5 horas.

In [4]:
query = sqla.text("""
  SELECT *
  FROM movie
  WHERE runtime > 300
""")
pd.read_sql(query, conn)

,id,created_date,modified_date,available_globally,locale,original_title,release_date,runtime,title
0,5793,2024-01-01,2024-01-01,b'\x00',None,日本統一シリーズ: 映画シリーズ,None,3892,Nihontouitsu Series: Film Series
1,5794,2024-01-01,2024-01-01,b'\x00',None,釣りバカ日誌: 映画シリーズ,None,2120,Free and Easy Series: Film Series
2,5874,2024-01-01,2024-01-01,b'\x01',None,None,2021-08-06,312,Navarasa: Limited Series
3,9729,2024-01-01,2024-01-01,b'\x00',None,織田同志会 織田征仁: 映画シリーズ,None,710,Seiji Oda: Film Series
4,9730,2024-01-01,2024-01-01,b'\x00',None,キングダム～首領になった男～: 映画シリーズ,None,427,Kingdom ~ The Man Who Became the Top ~: Film S...

**Respuesta 1:** Hay **5 películas** con duración mayor a 5 horas (`runtime` > 300 minutos). Cuatro son colecciones japonesas ("Film Series") y una es *Navarasa: Limited Series*. Por eso algunas duran tanto, como los 3,892 minutos de *Nihontouitsu Series*: en realidad son varias películas agrupadas en un solo registro, no una sola película.

2.	¿Cuál es el porcentaje de películas disponibles únicamente en EU en relación con el total, excluyendo los valores `NULL`? La consulta SQL debe entregar directamente el porcentaje final. No se deben devolver resultados parciales para realizar el cálculo en Python.

In [5]:
query = sqla.text("""
  SELECT ROUND(100 * SUM(available_globally = 0) / COUNT(*), 2) AS porcentaje_solo_eu
  FROM movie
  WHERE available_globally IS NOT NULL
""")
pd.read_sql(query, conn)

   porcentaje_solo_eu
0               83.57

**Respuesta 2:** El **83.57 %** de las películas con valor registrado en `available_globally` están disponibles **únicamente en EU** (`available_globally = 0`). Solo alrededor del 16 % se ofrece fuera de EU.

3.	¿Cuáles son los idiomas o regiones originales en la tabla de películas?
* ¿Cuántos registros tienen el campo `locale` con valor `NULL`? (NULL en SQL ⇔ None en Python)

In [6]:
query = sqla.text("""
  SELECT locale, COUNT(*) AS num_peliculas
  FROM movie
  GROUP BY locale
  ORDER BY num_peliculas DESC
""")
pd.read_sql(query, conn)

  locale  num_peliculas
0   None          11255
1     en            532

In [7]:
query = sqla.text("""
  SELECT COUNT(*) AS locale_null
  FROM movie
  WHERE locale IS NULL
""")
pd.read_sql(query, conn)

   locale_null
0        11255

**Respuesta 3:** En la tabla `movie` solo hay un idioma o región registrado: **`en` (inglés), con 532 películas**. Los otros **11,255 registros tienen `locale` en `NULL`** (aparecen como `None` en Python). Es decir, a la gran mayoría de las películas (≈95 %) les falta el idioma original.

4.	Asumiendo que los valores `NULL` en `locale` corresponden a otro idioma (diferente del inglés), el título original de la película NO debería coincidir con el título principal en dichos registros.
* Determina cuántas películas tienen títulos diferentes en estos dos campos (`title` y `original_title`).
*  ¿Coinciden los resultados (cantidad de `NULL` y títulos diferentes)? Si no es así, identifica qué características tienen los registros restantes.
* Finalmente, concluye si la suposición de que los valores `NULL` en `locale` indican que la película está en otro idioma es válida.

In [8]:
query = sqla.text("""
  SELECT COUNT(*) AS titulos_diferentes
  FROM movie
  WHERE title <> original_title
""")
pd.read_sql(query, conn)

   titulos_diferentes
0                3947

In [9]:
# Cruce entre locale y coincidencia de títulos
query = sqla.text("""
  SELECT locale,
         SUM(title <> original_title) AS titulos_diferentes,
         SUM(title = original_title) AS titulos_iguales,
         SUM(original_title IS NULL) AS sin_titulo_original,
         COUNT(*) AS total
  FROM movie
  GROUP BY locale
""")
pd.read_sql(query, conn)

  locale  titulos_diferentes  titulos_iguales  sin_titulo_original  total
0   None              3947.0             17.0               7291.0  11255
1     en                 NaN              NaN                532.0    532

In [10]:
# Películas con locale NULL cuyo título coincide con el original
query = sqla.text("""
  SELECT id, title, original_title, release_date
  FROM movie
  WHERE locale IS NULL AND title = original_title
""")
pd.read_sql(query, conn)

,id,title,original_title,release_date
0,1089,Recep Ivedik 7,Recep İvedik 7,None
1,1349,Veronica,Verónica,None
2,3509,Fantomas,Fantômas,None
3,3611,Luccas Neto em: O Hotel Magico,Luccas Neto em: O Hotel Mágico,None
4,4566,Un Dia En El Paraiso,Un día en el paraíso,None
5,5077,Superlopez,Superlópez,None
6,5211,Baris Akarsu Merhaba,Barış Akarsu Merhaba,None
7,5684,Totem,Tótem,None
8,6427,La Pena Maxima,La pena máxima,None
9,6530,Mirciulica,Mirciulică,None
10,7205,Animas,Ánimas,2019-01-25
11,7519,Dejame Vivir,Déjame Vivir,None
12,7726,Gangster Ka: African,Gangster Ka: Afričan,None
13,8459,Party Hard,Párty Hárd,None
14,10358,Extasis,Éxtasis,None
15,10592,Malefique,Maléfique,None
16,11031,Tiramisu,Tiramisù,None

**Respuesta 4:**


* **3,947 películas** tienen `title` diferente de `original_title`.
* **No coinciden** con los **11,255** registros con `locale` en `NULL`: faltan **7,308**. La tabla de cruce muestra sus características:
  * **7,291** películas con `locale` en `NULL` **no tienen `original_title`** (es `NULL`), así que no se pueden comparar. Muchas son producciones en inglés, como *Damsel*, *Lift*, *The Super Mario Bros. Movie* o *The Boss Baby*.
  * **17** películas con `locale` en `NULL` aparecen con títulos "iguales", pero en realidad **solo difieren en acentos o caracteres especiales**: *Verónica*, *Superlópez*, *Barış Akarsu Merhaba*, *Mirciulică*, *Tiramisù*. MySQL las considera iguales porque su comparación de texto ignora los acentos. Son títulos en español, portugués, turco, rumano, italiano, etc., así que **sí están en otro idioma**.
  * Las 532 películas con `locale = 'en'` tampoco tienen `original_title`.
* **Conclusión:** la suposición **no es válida** en general. Cuando el registro tiene `original_title`, se cumple: los 3,947 títulos diferentes y los 17 que solo difieren en acentos corresponden a películas en otro idioma. Pero la mayoría de los `NULL` en `locale` (7,291) no tienen título original y muchas son películas en inglés. Por lo tanto, el `NULL` en `locale` indica sobre todo que **falta el dato**, no que la película esté en otro idioma.

5.	Determina el título de la película que ha permanecido más tiempo en el top 10.

In [11]:
query = sqla.text("""
  SELECT DISTINCT m.title, v.cumulative_weeks_in_top10
  FROM view_summary v
  JOIN movie m ON m.id = v.movie_id
  WHERE v.cumulative_weeks_in_top10 = (
    SELECT MAX(cumulative_weeks_in_top10)
    FROM view_summary
    WHERE movie_id IS NOT NULL
  )
""")
pd.read_sql(query, conn)

           title  cumulative_weeks_in_top10
0  The Boss Baby                         22

**Respuesta 5:** La película que ha permanecido más tiempo en el top 10 es ***The Boss Baby***, con **22 semanas acumuladas**, considerando todos los registros de `view_summary`. No hay empates con ese valor máximo.

6.	Identifica los 5 programas de TV con mayor cantidad de temporadas.

In [12]:
query = sqla.text("""
  SELECT t.title, COUNT(s.id) AS num_temporadas
  FROM tv_show t
  JOIN season s ON s.tv_show_id = t.id
  GROUP BY t.id, t.title
  ORDER BY num_temporadas DESC
  LIMIT 5
""")
pd.read_sql(query, conn)

                               title  num_temporadas
0                     Grey's Anatomy              20
1                   Naruto Shippuden              20
2                   Heartland (2007)              17
3  It's Always Sunny in Philadelphia              16
4                               NCIS              15

**Respuesta 6:** Los 5 programas de TV con más temporadas registradas son:

1. *Grey's Anatomy*: 20 temporadas
2. *Naruto Shippuden*: 20 temporadas
3. *Heartland (2007)*: 17 temporadas
4. *It's Always Sunny in Philadelphia*: 16 temporadas
5. *NCIS*: 15 temporadas

7.	¿Cuáles son los intervalos de fechas de los resúmenes en la tabla `view_summary` de los períodos (`duration`) semestrales?

In [13]:
query = sqla.text("""
  SELECT DISTINCT start_date, end_date
  FROM view_summary
  WHERE duration = 'SEMI_ANNUALLY'
  ORDER BY start_date
""")
pd.read_sql(query, conn)

   start_date    end_date
0  2023-07-01  2023-12-31
1  2024-01-01  2024-06-30

**Respuesta 7:** En `view_summary` hay dos períodos semestrales (`SEMI_ANNUALLY`):

* **2023-07-01 a 2023-12-31** (segundo semestre de 2023)
* **2024-01-01 a 2024-06-30** (primer semestre de 2024)

En la pregunta 8 se usa el segundo, que inicia el 2024-01-01.

8.	Ordena las temporadas de *Grey's Anatomy* según la cantidad de vistas registradas en el primer período semestral de 2024.
* ¿Cómo interpretarías los resultados obtenidos?

In [14]:
query = sqla.text("""
  SELECT s.title, s.season_number, v.views, v.hours_viewed
  FROM view_summary v
  JOIN season s ON s.id = v.season_id
  JOIN tv_show t ON t.id = s.tv_show_id
  WHERE t.title LIKE 'Grey%s Anatomy'
    AND v.duration = 'SEMI_ANNUALLY'
    AND v.start_date = '2024-01-01'
  ORDER BY v.views DESC, s.season_number
""")
pd.read_sql(query, conn)

                        title  season_number    views  hours_viewed
0    Grey's Anatomy: Season 1              1  3600000      23400000
1    Grey's Anatomy: Season 2              2  3100000      60600000
2    Grey's Anatomy: Season 3              3  2900000      53700000
3    Grey's Anatomy: Season 4              4  2900000      35300000
4    Grey's Anatomy: Season 5              5  2900000      49300000
5    Grey's Anatomy: Season 6              6  2800000      48000000
6    Grey's Anatomy: Season 7              7  2700000      43000000
7    Grey's Anatomy: Season 8              8  2600000      44700000
8    Grey's Anatomy: Season 9              9  2500000      43300000
9   Grey's Anatomy: Season 10             10  2400000      41700000
10  Grey's Anatomy: Season 11             11  2200000      39400000
11  Grey's Anatomy: Season 12             12  2000000      35200000
12  Grey's Anatomy: Season 13             13  2000000      33300000
13  Grey's Anatomy: Season 14             14  2000000      33300000
14  Grey's Anatomy: Season 19             19  2000000      28600000
15  Grey's Anatomy: Season 15             15  1900000      33800000
16  Grey's Anatomy: Season 16             16  1800000      27300000
17  Grey's Anatomy: Season 17             17  1700000      20300000
18  Grey's Anatomy: Season 18             18  1700000      24400000
19  Grey's Anatomy: Season 20             20   100000        800000

**Respuesta 8:** En el primer semestre de 2024, la **Temporada 1** fue la más vista (**3.6 M** de vistas), seguida por la 2 (3.1 M) y las 3, 4 y 5 (2.9 M cada una). Las vistas bajan casi en orden hasta las temporadas 17 y 18 (1.7 M). La **Temporada 20** es la última, con apenas **0.1 M**. Cuando hay empate en vistas, se ordena por número de temporada.

**Interpretación:**

* **Efecto embudo:** muchos usuarios empiezan la serie desde el principio, pero conforme avanzan las temporadas una parte la abandona. Con 20 temporadas, solo un público fiel llega a las más recientes.
* **Vistas vs. horas:** la Temporada 1 tiene más vistas pero menos horas que la 2 (23.4 M vs. 60.6 M). Esto se debe a que es una temporada corta (9 episodios), y Netflix calcula las vistas como horas vistas entre duración de la temporada.
* **Excepciones:** la Temporada 19 (2.0 M) supera a las 15 a 18. Probablemente se agregó recientemente al catálogo y atrajo a la audiencia que sigue la serie al día. La Temporada 20 tiene muy pocas vistas porque se estrenó en 2024 y seguramente estuvo disponible solo una parte del semestre.

9.	Todas las consultas anteriores podrían hacerse también con la lógica relacional implementada en Pandas, que permite replicar la mayoría de las operaciones de SQL. Si los dataframes se han llenado como sigue, resuelve la consulta 8 utilizando las funciones de Pandas.

In [15]:
tv_show = pd.read_sql(sqla.text('SELECT * FROM tv_show'), conn)
season = pd.read_sql(sqla.text('SELECT * FROM season'), conn)
view_summary = pd.read_sql(sqla.text('SELECT * FROM view_summary'), conn)

In [16]:
vs = view_summary[(view_summary['duration'] == 'SEMI_ANNUALLY') &
                  (pd.to_datetime(view_summary['start_date']) == '2024-01-01')]
greys = tv_show[tv_show['title'].str.match(r"Grey.s Anatomy")]

resultado = (vs.merge(season, left_on='season_id', right_on='id', suffixes=('_vs', ''))
               .merge(greys[['id']], left_on='tv_show_id', right_on='id', suffixes=('', '_show'))
               [['title', 'season_number', 'views', 'hours_viewed']]
               .sort_values(['views', 'season_number'], ascending=[False, True]))
resultado

                        title  season_number    views  hours_viewed
0    Grey's Anatomy: Season 1            1.0  3600000      23400000
1    Grey's Anatomy: Season 2            2.0  3100000      60600000
2    Grey's Anatomy: Season 3            3.0  2900000      53700000
4    Grey's Anatomy: Season 4            4.0  2900000      35300000
3    Grey's Anatomy: Season 5            5.0  2900000      49300000
5    Grey's Anatomy: Season 6            6.0  2800000      48000000
6    Grey's Anatomy: Season 7            7.0  2700000      43000000
7    Grey's Anatomy: Season 8            8.0  2600000      44700000
8    Grey's Anatomy: Season 9            9.0  2500000      43300000
9   Grey's Anatomy: Season 10           10.0  2400000      41700000
10  Grey's Anatomy: Season 11           11.0  2200000      39400000
11  Grey's Anatomy: Season 12           12.0  2000000      35200000
12  Grey's Anatomy: Season 13           13.0  2000000      33300000
13  Grey's Anatomy: Season 14           14.0  2000000      33300000
14  Grey's Anatomy: Season 19           19.0  2000000      28600000
15  Grey's Anatomy: Season 15           15.0  1900000      33800000
16  Grey's Anatomy: Season 16           16.0  1800000      27300000
18  Grey's Anatomy: Season 17           17.0  1700000      20300000
17  Grey's Anatomy: Season 18           18.0  1700000      24400000
19  Grey's Anatomy: Season 20           20.0   100000        800000

**Respuesta 9:** Con Pandas se obtiene **el mismo resultado** que en la pregunta 8, las mismas 20 temporadas en el mismo orden. Las equivalencias con SQL son:

* Los filtros booleanos sobre `view_summary` y `tv_show` hacen el papel del `WHERE`.
* `merge` reemplaza a los `JOIN` entre `view_summary`, `season` y `tv_show`.
* `[[...]]` hace el papel del `SELECT` de columnas.
* `sort_values` reemplaza al `ORDER BY`.

`season_number` aparece con decimales (por ejemplo, 1.0) por la conversión de tipos que hace Pandas al cargar y unir los datos. Esto no afecta el resultado.

`MySQL` es un sistema de gestión de bases de datos relacional, pero desde Python también es posible extraer información de bases de datos no relacionales, como `Firestore`, `MongoDB` o `Cassandra`, utilizando conectores o integraciones específicas. Esto permite combinar datos de diferentes fuentes según las necesidades del análisis o la aplicación.

En el siguiente ejercicio usarás un ejemplo con `Firestore` desde Python. Para ello utilizarás los módulos `credentials` y `firestore` de la biblioteca `firebase_admin`.

In [17]:
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

En `Firestore`, a diferencia de `MySQL` donde se utiliza un usuario y contraseña para conectarse, la autenticación se realiza mediante un archivo JSON que almacena las credenciales necesarias para acceder a la base de datos. Este archivo contiene las claves y la información de configuración que permiten a Python establecer la conexión de manera segura.

In [18]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [19]:
# Debes descargar el archivo de credenciales "consultancy.json" (disponible en las instrucciones de Canvas) y ubicarte en la carpeta donde lo almacenaste
import os
DIR = "/content/drive/MyDrive/Colab Notebooks/MNA - CyA de Datos/3.2 Actividad 3 | Acceso BD y manipulación de datos"
os.chdir(DIR)

In [20]:
# consultancy.json almacena la clave privada para autenticar una cuenta y autorizar el acceso a los servicios
# A través de la función Certificate(), se regresa una credencial inicializada, que puedes utilizar para crear una nueva instancia de la aplicación
cred = credentials.Certificate('consultancy.json')
firebase_admin.initialize_app(cred)
db = firestore.client()

10.	Investiga cómo leer la colección `EMPLOYEE` y mostrar su contenido en un dataframe. Asegúrate de incluir el `id` en el resultado

In [21]:
docs = db.collection('EMPLOYEE').stream()
employee = pd.DataFrame([{'id': d.id, **d.to_dict()} for d in docs]).set_index('id')
employee

                     emp_fname   emp_lname              emp_hiredate
id
8LcLuxVHGAd2d9IQc5jF     David      Senior 1989-07-12 06:00:00+00:00
Fzd60D6Z2CU4n0wVV8YN   William  Smithfield 2004-06-04 05:00:00+00:00
lX5xuQ5w3i6ib2ExccWY      John        News 2000-11-08 06:00:00+00:00
yocFj2lichOkbAj9NBfp      June     Arbough 1996-12-01 06:00:00+00:00

**Respuesta 10:** Con `credentials.Certificate()` se autentica en Firestore usando `consultancy.json`, y con `stream()` se leen los documentos de la colección `EMPLOYEE`. Cada documento se convierte a diccionario con `to_dict()`, y su identificador se agrega con `d.id` y se usa como índice del dataframe. El resultado muestra los **4 empleados** con su nombre, apellido y fecha de contratación, como se pide.

In [22]:
firebase_admin.delete_app(firebase_admin.get_app())

---

**Declaración de uso de IA**

* Anthropic. (2026). *Claude (Opus 5.5)*, como herramienta de apoyo para recordar comandos y sintaxis, así como para resolver dudas sobre el funcionamiento de Google Colab. La elaboración de la tarea y la revisión de los resultados fueron realizadas por mí. https://claude.ai/

---